---
exporter_path: /u01/exporters
elk_version: 8.13.4

exporter_files:
      - node_exporter
      - filebeat-{{elk_version}}-x86_64.rpm

exporter_services:
      - node-exporter

exporter_services_full:
      - node-exporter
      - filebeat

startup_filebeat:
      - filebeat modules enable logstash
      - filebeat setup