---
- name: copy rpm file of grafana
  copy:
    src: files/grafana-enterprise-{{grafana_version}}.rpm
    dest: /tmp/grafana-enterprise-{{grafana_version}}.rpm

- name: install grafana
  yum:
    name: /tmp/grafana-enterprise-10.4.2-1.x86_64.rpm
    state: present

### RELOAD DAEMONS ###
- name: reload daemons
  systemd:
    daemon_reload: yes